/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'watches' : IDL.Null,
  'accessories' : IDL.Null,
  'sunglasses' : IDL.Null,
  'purses' : IDL.Null,
  'shoes' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
  'isTrending' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const Cart = IDL.Record({
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'product' : Product,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});
export const OrderSummary = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const WishlistItem = IDL.Record({
  'addedAt' : IDL.Int,
  'product' : Product,
});
export const Wishlist = IDL.Record({ 'items' : IDL.Vec(WishlistItem) });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderSummary' : IDL.Func([], [OrderSummary], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [Wishlist], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [Order], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedProducts' : IDL.Func([], [], []),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'watches' : IDL.Null,
    'accessories' : IDL.Null,
    'sunglasses' : IDL.Null,
    'purses' : IDL.Null,
    'shoes' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
    'isTrending' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const Cart = IDL.Record({
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Nat,
  });
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'product' : Product,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  const OrderSummary = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const WishlistItem = IDL.Record({ 'addedAt' : IDL.Int, 'product' : Product });
  const Wishlist = IDL.Record({ 'items' : IDL.Vec(WishlistItem) });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderSummary' : IDL.Func([], [OrderSummary], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [Wishlist], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [Order], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedProducts' : IDL.Func([], [], []),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };