/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem>, 'totalPrice' : bigint }
export interface CartItem { 'quantity' : bigint, 'product' : Product }
export type Category = { 'watches' : null } |
  { 'accessories' : null } |
  { 'sunglasses' : null } |
  { 'purses' : null } |
  { 'shoes' : null };
export interface Order {
  'id' : bigint,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'quantity' : bigint,
  'price' : bigint,
  'product' : Product,
}
export interface OrderSummary {
  'totalOrders' : bigint,
  'totalRevenue' : bigint,
}
export interface Product {
  'id' : bigint,
  'inStock' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'isBestSeller' : boolean,
  'isTrending' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wishlist { 'items' : Array<WishlistItem> }
export interface WishlistItem { 'addedAt' : bigint, 'product' : Product }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBestSellers' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getOrderSummary' : ActorMethod<[], OrderSummary>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getTrendingProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Wishlist>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], Order>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedProducts' : ActorMethod<[], undefined>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateProduct' : ActorMethod<[bigint, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];