/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OrderSummary {
    totalOrders: bigint;
    totalRevenue: bigint;
}
export interface Wishlist {
    items: Array<WishlistItem>;
}
export interface OrderItem {
    quantity: bigint;
    price: bigint;
    product: Product;
}
export interface WishlistItem {
    addedAt: bigint;
    product: Product;
}
export interface CartItem {
    quantity: bigint;
    product: Product;
}
export interface Cart {
    items: Array<CartItem>;
    totalPrice: bigint;
}
export interface Order {
    id: bigint;
    timestamp: bigint;
    items: Array<OrderItem>;
    totalPrice: bigint;
}
export interface Product {
    id: bigint;
    inStock: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isBestSeller: boolean;
    isTrending: boolean;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    watches = "watches",
    accessories = "accessories",
    sunglasses = "sunglasses",
    purses = "purses",
    shoes = "shoes"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addToCart(productId: bigint, quantity: bigint): Promise<void>;
    addToWishlist(productId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getBestSellers(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Cart>;
    getOrderHistory(): Promise<Array<Order>>;
    getOrderSummary(): Promise<OrderSummary>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    getTrendingProducts(): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWishlist(): Promise<Wishlist>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(): Promise<Order>;
    removeFromCart(productId: bigint): Promise<void>;
    removeFromWishlist(productId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedProducts(): Promise<void>;
    updateCartQuantity(productId: bigint, quantity: bigint): Promise<void>;
}
import type { Cart as _Cart, CartItem as _CartItem, Category as _Category, Order as _Order, OrderItem as _OrderItem, Product as _Product, UserProfile as _UserProfile, UserRole as _UserRole, Wishlist as _Wishlist, WishlistItem as _WishlistItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async addToWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBestSellers(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestSellers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestSellers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_Cart_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_Cart_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderHistory(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderHistory();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderHistory();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderSummary(): Promise<OrderSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderSummary();
            return result;
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingProducts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingProducts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Wishlist> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return from_candid_Wishlist_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return from_candid_Wishlist_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder();
                return from_candid_Order_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder();
            return from_candid_Order_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async removeFromWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
    async updateCartQuantity(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartQuantity(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CartItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Cart_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Cart {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_WishlistItem_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WishlistItem): WishlistItem {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Wishlist_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Wishlist): Wishlist {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_CartItem>;
    totalPrice: bigint;
}): {
    items: Array<CartItem>;
    totalPrice: bigint;
} {
    return {
        items: from_candid_vec_n17(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: bigint;
    product: _Product;
}): {
    quantity: bigint;
    product: Product;
} {
    return {
        quantity: value.quantity,
        product: from_candid_Product_n8(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    timestamp: bigint;
    items: Array<_OrderItem>;
    totalPrice: bigint;
}): {
    id: bigint;
    timestamp: bigint;
    items: Array<OrderItem>;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        timestamp: value.timestamp,
        items: from_candid_vec_n23(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: bigint;
    price: bigint;
    product: _Product;
}): {
    quantity: bigint;
    price: bigint;
    product: Product;
} {
    return {
        quantity: value.quantity,
        price: value.price,
        product: from_candid_Product_n8(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_WishlistItem>;
}): {
    items: Array<WishlistItem>;
} {
    return {
        items: from_candid_vec_n28(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    addedAt: bigint;
    product: _Product;
}): {
    addedAt: bigint;
    product: Product;
} {
    return {
        addedAt: value.addedAt,
        product: from_candid_Product_n8(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inStock: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isBestSeller: boolean;
    isTrending: boolean;
}): {
    id: bigint;
    inStock: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isBestSeller: boolean;
    isTrending: boolean;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount,
        isBestSeller: value.isBestSeller,
        isTrending: value.isTrending
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    watches: null;
} | {
    accessories: null;
} | {
    sunglasses: null;
} | {
    purses: null;
} | {
    shoes: null;
}): Category {
    return "watches" in value ? Category.watches : "accessories" in value ? Category.accessories : "sunglasses" in value ? Category.sunglasses : "purses" in value ? Category.purses : "shoes" in value ? Category.shoes : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WishlistItem>): Array<WishlistItem> {
    return value.map((x)=>from_candid_WishlistItem_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inStock: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isBestSeller: boolean;
    isTrending: boolean;
}): {
    id: bigint;
    inStock: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isBestSeller: boolean;
    isTrending: boolean;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount,
        isBestSeller: value.isBestSeller,
        isTrending: value.isTrending
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    watches: null;
} | {
    accessories: null;
} | {
    sunglasses: null;
} | {
    purses: null;
} | {
    shoes: null;
} {
    return value == Category.watches ? {
        watches: null
    } : value == Category.accessories ? {
        accessories: null
    } : value == Category.sunglasses ? {
        sunglasses: null
    } : value == Category.purses ? {
        purses: null
    } : value == Category.shoes ? {
        shoes: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
